apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dendrite
  namespace: matrix
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - matrix.example.com
      secretName: matrix-example-com-tls
  rules:
    - host: matrix.example.com
      http:
        paths:
          - path: /_matrix
            pathType: Prefix
            backend:
              service:
                name: dendrite
                port:
                  number: 8008